import type { PlasmoCSConfig } from 'plasmo';

import { Storage } from '@plasmohq/storage';

import { Option } from '~contents/constants';

export const config: PlasmoCSConfig = {
  matches: ['https://*/*'],
  all_frames: true,
};

// The content script generated by plasmo is a nested IIFE, and Top-level await cannot be used.
(async function preventTranslation() {
  const storage = new Storage({ area: 'local' });
  const onOffExtension = await storage.get(Option.preventTranslateCode);
  if (!onOffExtension) {
    return;
  }

  const preElements = document.getElementsByTagName('pre');
  for (const pre of preElements) {
    pre.setAttribute('translate', 'no');
  }

  const observer = new MutationObserver((records) => {
    const preElements = records
      .filter((record) => record.type === 'childList')
      .flatMap((record) => Array.from(record.addedNodes))
      .filter((node) => node.nodeType === Node.ELEMENT_NODE)
      .flatMap((node) => Array.from((node as Element).querySelectorAll('pre')));

    for (const pre of preElements) {
      pre.setAttribute('translate', 'no');
    }
  });

  observer.observe(document.body, { childList: true, subtree: true });
})();
